### ISSUE TITLE
Using !hangar save while seating in the grid leads to spectator mode

### ISSUE THREAD

**Issue by kontu** [Casimir255/QuantumHangar#23]
Using !hangar save while seating in the grid leads to spectator mode

While granted they can only explore grids within sync distance, it can still be a bit troublesome. is there a way we can ensure they are ejected from the grid (or not allow saving while seated in a grid); or just force kill them if they're in a grid when they save?

**Comment by MisterRee** [comment]
@BobDaRoss to narrow it down, this bug was initially addressed in [Issue #2 ](https://github.com/BobDaRoss/QuantumHangar/issues/2) ([Commit 1c76c76](https://github.com/BobDaRoss/QuantumHangar/commit/1c76c76806ad5211a05328a870b4d6a2f8b866f5)) but has been reintroduced by a recent commit, possibly [Commit 13b1549](https://github.com/BobDaRoss/QuantumHangar/commit/13b15498380403d67b8c8045ee6c21e3e16f3b79#diff-5e6295765e2b0da2b098c18d370ab5a2bb81ee156d1f6d9201c7b5deea66640a).

**Comment by Casimir255** [comment]
Yeah I thought i fixed this already tbh.

**Comment by Casimir255** [comment]
Ahh, im doing it too late. I can fix this

**Comment by Casimir255** [comment]
Issue has been fixed

**Comment by kontu** [comment]
This still occurs in v2.4.55; unsure if that version included this commit or not
